parameters:
#    magiseo_crawler.example.class: Magiseo\CrawlerBundle\Example

services:
#    magiseo_crawler.example:
#        class: %magiseo_crawler.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
